/**
 * @fileoverview gRPC-Web generated client stub for game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: src/proto/game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.game = require('./game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.CreateGameRequest,
 *   !proto.game.CreateGameResponse>}
 */
const methodDescriptor_GameService_CreateGame = new grpc.web.MethodDescriptor(
  '/game.GameService/CreateGame',
  grpc.web.MethodType.UNARY,
  proto.game.CreateGameRequest,
  proto.game.CreateGameResponse,
  /**
   * @param {!proto.game.CreateGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.CreateGameResponse.deserializeBinary
);


/**
 * @param {!proto.game.CreateGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.CreateGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.CreateGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.createGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/CreateGame',
      request,
      metadata || {},
      methodDescriptor_GameService_CreateGame,
      callback);
};


/**
 * @param {!proto.game.CreateGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.CreateGameResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.createGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/CreateGame',
      request,
      metadata || {},
      methodDescriptor_GameService_CreateGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.JoinGameRequest,
 *   !proto.game.JoinGameResponse>}
 */
const methodDescriptor_GameService_JoinGame = new grpc.web.MethodDescriptor(
  '/game.GameService/JoinGame',
  grpc.web.MethodType.UNARY,
  proto.game.JoinGameRequest,
  proto.game.JoinGameResponse,
  /**
   * @param {!proto.game.JoinGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.JoinGameResponse.deserializeBinary
);


/**
 * @param {!proto.game.JoinGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.JoinGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.JoinGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.joinGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame,
      callback);
};


/**
 * @param {!proto.game.JoinGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.JoinGameResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.joinGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.UpdateGameStateRequest,
 *   !proto.game.UpdateGameStateResponse>}
 */
const methodDescriptor_GameService_UpdateGameState = new grpc.web.MethodDescriptor(
  '/game.GameService/UpdateGameState',
  grpc.web.MethodType.UNARY,
  proto.game.UpdateGameStateRequest,
  proto.game.UpdateGameStateResponse,
  /**
   * @param {!proto.game.UpdateGameStateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.UpdateGameStateResponse.deserializeBinary
);


/**
 * @param {!proto.game.UpdateGameStateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.UpdateGameStateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.UpdateGameStateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.updateGameState =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/UpdateGameState',
      request,
      metadata || {},
      methodDescriptor_GameService_UpdateGameState,
      callback);
};


/**
 * @param {!proto.game.UpdateGameStateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.UpdateGameStateResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.updateGameState =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/UpdateGameState',
      request,
      metadata || {},
      methodDescriptor_GameService_UpdateGameState);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.StreamGameUpdatesRequest,
 *   !proto.game.StreamGameUpdatesResponse>}
 */
const methodDescriptor_GameService_StreamGameUpdates = new grpc.web.MethodDescriptor(
  '/game.GameService/StreamGameUpdates',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.game.StreamGameUpdatesRequest,
  proto.game.StreamGameUpdatesResponse,
  /**
   * @param {!proto.game.StreamGameUpdatesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.StreamGameUpdatesResponse.deserializeBinary
);


/**
 * @param {!proto.game.StreamGameUpdatesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.StreamGameUpdatesResponse>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.streamGameUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/StreamGameUpdates',
      request,
      metadata || {},
      methodDescriptor_GameService_StreamGameUpdates);
};


/**
 * @param {!proto.game.StreamGameUpdatesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.StreamGameUpdatesResponse>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServicePromiseClient.prototype.streamGameUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/StreamGameUpdates',
      request,
      metadata || {},
      methodDescriptor_GameService_StreamGameUpdates);
};


module.exports = proto.game;

